### PR TITLE
Highlighting matches for bookmark and history search

### LINKED ISSUE #35: Add match highlighting to bookmark and history modes
In tab search mode, as you type in a search string, matching text in each suggestion is displayed in bold font. The fuze library does this automatically.

It would be nice to add this functionality to the bookmark and history modes. These modes currently use chrome's built in search, which doesn't provide any match highlighting, but you can manually search for matching substrings in the suggestions.

### PR DESCRIPTION
**Pull request by pureooze**
Added highlighting matches for bookmark and history search

Fixes #35

### CODE REVIEW

**Comment by eejdoowad** [comment]
If you plant to use this approach to highlighting (running fuze after getting all search results), make sure to set the fuze threshold so that all suggestions are kept.

I had a simpler approach in mind : manually calculate substring matches when rendering the suggestion.

**Comment by pureooze** [comment]
Are there downsides of relying on Fuse to do the matching vs manually calculating it? It just seemed to me that Fuse made sense since we use it in the other search modes.

**Comment by pureooze** [comment]
So I messed around with Fuse using http://fusejs.io/

Looks like a fuse threshold of 1 will make sure no results are actually removed from the list. I'm just wondering if this is useful to users, when searching using a different mode like tabs, Saka uses a threshold of 0.5. Is there a reason this doesn't make sense for bookmarks/history?

Also the shouldSort parameter seems to order based on the score of the object so I think using this makes sense as it allows users to see better matches higher in the list.

Thoughts?

**Comment by pureooze** [comment]
I find your thoughts useful, and I find I learn better when I discuss my ideas with others so I don't mind discussing before merging at all.

I think it makes sense to allow users to configure if they want fuzzy search ordering or not, it really does feel like it comes down to preference. As for the threshold, I forgot that bookmark and history work differently than the tab search, since they filter using the browser APIs. It does make sense not to filter a second time so I think I will end up just setting the threshold to 1 so that it doesn't remove any entry from the results.

**Pull request merged**
